# Generated by Django 4.2.7 on 2023-11-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productbrand_alter_product_slug_alter_product_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='is_delete',
        ),
    ]
