# Generated by Django 4.2.7 on 2023-11-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_productcategory_alter_product_slug_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=300, verbose_name='Color')),
                ('size', models.CharField(max_length=300, verbose_name='Size')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_module.productcategory', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_information', to='product_module.productinformation', verbose_name='complite information'),
        ),
    ]
