# Generated by Django 4.2.7 on 2023-12-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_remove_productbrand_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='Product Image'),
        ),
    ]
