# Generated by Django 5.0 on 2023-12-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_slider_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.TextField(max_length=500, verbose_name='لینک'),
        ),
    ]
