# Generated by Django 4.2.7 on 2023-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('full_name', models.CharField(max_length=300, verbose_name='full name')),
                ('message', models.TextField(verbose_name='massage')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='is read by admin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('response', models.TextField(blank=True, null=True, verbose_name='response')),
            ],
            options={
                'verbose_name': 'contact us',
                'verbose_name_plural': 'contact us list',
            },
        ),
    ]
