# Generated by Django 5.0 on 2023-12-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
